apiVersion: apps/v1
kind: Deployment
metadata:
  name: directory-website
spec:
  template:
    spec:
      containers:
        - name: directory-website
          env:
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: directoryfe-secret
                  key: APP_ENV
            - name: NEXT_PUBLIC_APP_ENV
              valueFrom:
                secretKeyRef:
                  name: directoryfe-secret
                  key: NEXT_PUBLIC_APP_ENV
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: directoryfe-secret
                  key: APP_URL
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: directoryfe-secret
                  key: AUTH_TOKEN
            - name: ES_URL
              valueFrom:
                secretKeyRef:
                  name: directoryfe-secret
                  key: ES_URL
            - name: ES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: directoryfe-secret
                  key: ES_API_KEY
